version: '3'

services:
  minitwit-app:
    build: .
    command: >
      sh -c "
            python ITU_MiniTwit/manage.py migrate &&
            python ITU_MiniTwit/manage.py runserver 0.0.0.0:8000"
    environment:
      MYSQL_DATABASE: mysqlDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
    ports:
      -  8000:8000
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    image: petrastm/mysqlimage
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqlDB
    ports:
      - '3306:3306'
